# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='actualizado',
            new_name='update',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
